---
- name: Loading OS specific variables
  include_vars: '{{ ansible_pkg_mgr }}.yml'

- name: Installing service packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - '{{ pkgs }}'

- name: Updating /etc/rsyslog.conf to forward logs
  lineinfile:
    path: /etc/rsyslog.conf
    line: '*.* @@{{syslog_server}}'

- name: Starting and enabling service
  service:
    name: '{{ service_name }}'
    state: started
    enabled: yes
