---
- name: Loading OS specific variables
  include_vars: '{{ ansible_pkg_mgr }}.yml'

- name: Installing packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - '{{ helper_pkgs }}'
    - '{{ perf_pkgs }}'
  when: ansible_pkg_mgr=='yum'
