---
- hosts: all
  tasks:
    - name: Checking for CentOS 
      fail:
        msg: 'Playbook works only on CentOS distro.'
      when: not ansible_os_family == "RedHat"

    - name: Loading common variables
      include_vars: 'common.yml'

    - name: Loading CentOS variables
      include_vars: '{{ ansible_os_family }}.yml'

    - name: Getting helper packages
      yum:
          name: '{{ item }}'
          state: present
      with_items: 
        - "{{ helper_pkgs }}"

    - name: Making /opt/software folder
      file:
        path: /opt/software
        state: directory 

    - name: 'Cloning git repo: {{ ansible_git_url }} to {{ ansible_build_area }}'
      git:
        repo: '{{ ansible_git_url }}'
        dest: '{{ ansible_build_area }}'
        version: '{{ ansible_stable_version }}'

    - name: 'Building ansible {{ ansible_stable_version }}'
      shell: 'cd {{ ansible_build_area }} && make rpm'
