---
- name: Sending authorized keys to host
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - public_keys/*

- name: Updating /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: '{{ item }}'
  with_items:
    - AddressFamily inet
    - ListenAddress 0.0.0.0

- name: Permitting root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin yes'
