---
- name: Importing OS specific variables
  include_vars: '{{ ansible_pkg_mgr }}.yml'

- name: Installing service packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - '{{ pkgs }}'
  when: ansible_pkg_mgr=='yum'

- name: Installing service packages
  apt:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - '{{ pkgs }}'
  when: ansible_pkg_mgr=='apt'

- name: Sending chrony.conf file
  template:
    src: 'chrony.conf.{{ ansible_pkg_mgr }}.j2'
    dest: /etc/chrony.conf
  when: ansible_pkg_mgr=='yum'


- name: Sending chrony.conf file
  template:
    src: 'chrony.conf.{{ ansible_pkg_mgr }}.j2'
    dest: /etc/chrony/chrony.conf
  when: ansible_pkg_mgr=='apt'

- name: Starting and enabling chrony client
  service:
    name: '{{ service_name }}'
    state: started
    enabled: yes

- name: Syncing system time with NTP servers
  command: timedatectl set-ntp yes
  changed_when: False
