---
- name: Installing sysbench
  yum:
    name: sysbench
    state: installed

- name: Creating sbtest database
  mysql_db:
    db: sbtest
    state: present

- name: Creating sbtest user
  mysql_user:
    user: sbtest
    host: "%"
    password: '' 
    priv: 'sbtest.*:ALL'
    state: present  
